name: outseta
description: API client for projects using the Outseta membership operating system.
version: 2.0.0
repository: https://github.com/dartfoundry/outseta

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  http: ^1.4.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  lints: ^6.0.0
  mockito: ^5.4.6
  test: ^1.26.2

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - api
  - client
  - rest
  - saas
  - membership
